//! Seed-to-stitch parity cases, on synthetic genomes. Expected alignments are STAR
//! 2.7.11b's on the same genome and reads (`--genomeSAindexNbases 5`, default
//! parameters).

use assert_cmd::cargo::cargo_bin_cmd;
use std::fs;
use std::io::Write;
use std::path::Path;
use tempfile::TempDir;

const SPLICE_GENOME: &str = concat!(
    "GAATATGTCTTAACTTCACTATGGTTACATTATCGAAGGTTGTGAAAGCTCTCCGGTTTATCCCTTAGCGGCACCACTGCCATGGCGCTTCAATGC",
    "CAGCGAGATTATCTATTCTGTACCTACGGTCCGAGTTGATCTGTGTTCTGGATTCTAAGTATTAACCTTCGGTCAATATCCCAATACCGGGGATGC",
    "AGGGTGAGCGAGTCTAGCACGCTAGCAACAATAACACAAAGCCCCTTGGAGGGATTCTACGAGGTGTTGAACAGATTATATGACGGGGTAGGCGCG",
    "TTACCTGTTGCACTCCCACAAAGCACTCGAAGTGTAAGCTTACTTGGTTGCTATCCTTCGTTTAATGCCGAACGCTCTATGGCCCCTAGCCGAGCA",
    "ACCTTCGAATATATTTGCCGCCACCGCTCCAGGCTAGATGTCACGGGGTGTCTTTATAGGGCGTTACCGCCGGGAGATAGCCGACTCCCGTGTATG",
    "GCGAGAATGTTGGACGCATTGCGGCTAGTCAGCAGGTACCGGCCATTAGTTATAGTTCGTGTGACCAGAGACGGGAGCCGACTATAAGTTGCAAGC",
    "TGGAGATTAGCGAGGAAGATGGTGTCGACCGGGGGGGGGTCAAGTAATTCGGTTCAGTGACCCTATGCCTGTGCTGCCACATGTCCCTAGGATTTT",
    "TGTACGCCCTCAGGCAACACTGCCCGAGAACGTTGTTAGAAGGACTAGCAACTCCTGGTGTATTCCGCCCGAGGCGAGCTTATTGTTGACATTAAG",
    "CTTTGTCTGAGTAGGGCTCGGGAATACACAGTCTTGGCGATTTGGCGAGCAATCTATTTTTACTGTAATTCTTGTAATGAGAGTATGCTCGGGGAT",
    "GCGGCTGGCACGACGTTTAGGCTCTTTGCCTCATGGAACCCTAAGGAAGATTTTGTCCAAGATGTGGGTGTTCTTCGTGGTTTAGACTTTGGTTGA",
    "AGGTATAGTCGAGAATCCTTGCGGGTGTGGGCGACATATCAACCTGTAATATGCAAGCGCATCTTAGCTTCTAGGAGTGCAATCCGAGGACCATGT",
    "CGGTGGCCGTGTGAAGCAAGGTCGGTGCTATGGCTTACGTAGTTATCTCGGGCTATAGTGTCCCTCATGTTAGGCATTGACGTTCCAGCACTTTGC",
    "AAAGGAGCTACTATTTGACGAGTATCGAGCATGTGAGACCGATAATCGCGCGTTAGTTGACGCTCAGGTACGACTGTAGAATGGGTGGGTGAGTCA",
    "TACAATAATGTGCTCTCATGGCCGGCGAAACGACTACATTTAAAGTTCGGGTCCAGGGTCACGATTACAATCCTGGAATTGATGCCAGTGCTAACT",
    "GTCCTCAGCTTTAGACTAACTATCTCACTTGTAATCAATTAGCGCACTAACGGCATTACCAAGTGTGTGCAGAAAGTATATAAGATGTTCTGTCAG",
    "TGGAAAAAATAGGCAACCCTACCATCTTGGCAAGATTTCGCCAAGCTTACCCTGAACACTACGCCGGTACACTACGAGGCATAGGCCGCGGTCCTT",
    "ACCAATGACCTTATGTGCAACTCTATCATTCCTCCCGGACGCCACCACCTTTGGCATACGAGTGACAGGAAAGAGACCAAGCGTTACGATACTTGT",
    "CTTGTTACTGCTTACAACGACGTGACACCTAACTTAAAGGACTGCTCATCAATCTTAGTTCTCGTTGTCAAAAAACTGCTCTCTTGAACATGTTCG",
    "GTCATAGAAGCCGTATGTTGCTCGCGTCAGTCACTGTCCGACACCCTCGATGAAAGGTCGAAGCTATACCCCTCCATTTGACTCGCGATCGTTCCA",
    "CGGTAACAATGTCATATTCGTGATACTAGTTGACAATAATTATTTGTCAGTGCAATCGCTCGTGTGTCTTGCCAGTCCTCTTTCCCGCGCCTGTCC",
    "GGACGATTAGAATTGCCTCCGTGTACTAACATAAACAAATTGGGAATGAACAGCATTCATACGCGGTTGGACATATGCATTAGGGTAAACTGAAGA",
    "GATCCAGAAACGGGACTGTCAGTATCCTAATAAATCTCCATTAATTGATACATAAGATGTTGAAGCGTCCGGAACGAGCGTAATCCACGCTAGCTG",
    "GCCGTAGGCCGTTGTATTTGCAGGGCCATCACTTACAATGGCCGGACTTATGAGCTATTACTTAGTGTCTATGAAGAAGAGGCGGGCTCAACATTG",
    "ATCAAACAAAATTCCCAGTCGAGGAGTAGATACCCCAATCTTAGGAATGAGTCACCCTCCCTGGAGGGCATGGTTGCCACCTGGGGCTATTGCGCA",
    "CCCCTCGGACAGAGGCGGTACGACTAACCACCTTTGGCATACCGAGGTGCGCTTGTGTCGCCAGCTCGCTCGTTGATGAACTCCAGTAAACTACAT",
    "TGTAACCTGCCGTTACGCACTTAGGCGCTCCCCTGGCGATATTGTGAGTCTATGCACCTTGAATCGAACCTGCGGTCATACGGATTCAGACATGAC",
    "CTCGAGAAGGCAGATTCTATTTAGAGGCCACTTTGACGGAACTTACGATAACGCGAAACCAGATTGTGAACCAGGCTTTCCGGACGAGTCGAATGA",
    "TCACACTTTCCACTGCGGCGCAATATGAAACGGACCGCTGCTGAGTCGACTGCTCACTGCCCAGGCGAGCGTCGACAGCTCTCACACGACCGATGA",
    "AGGTTACGCGCATACCACATTATAACAGATGCTTGGTTTGTGACGGCCTCGCACTTACTTACTTTACGTGGTGGCCGATGGTACTGGTACTACATT",
    "TTAAAGGCACGAGAATGCTCTCAGTCCTCTGCTCACGGCTTTTACGCGAAGAACTGAGAACTTACAACATTATTTGGAAGGTTAAGACCCATTCTT",
    "TTGGGTGCATTTCCCATTAACCGTCATAGACTAAGTAACAATTGTCATCCCTATGGGCGGTGAAAGCGCGGATCATACACGGAAGGACTCGTGAGC",
    "CCTACTAGTCATAGGGTGCACCGCGAACCTGATAGTGTCCTGTACGACCCCTTATGCAATCTGAGGCATGATTCTTTGGCTGCTCGTTCAAGGTAG",
    "TGTTTGACGGTACCATGTCACGACGTGGTAAGGTCCGGCATGGGCCAGGTCCAACGGTTTATATGCGTTGGGAATACAATCGCCATACAGTACAAG",
    "GAATGGTATGATATCAACTTTCGGAAACGCGGATAACACTCCTTCTTGCTAGATCCTTGAAGACGCTGTCAACTAAGACATCTGAGAGTATCTGAT",
    "GTGTCTGGTATATTCTTTAAAAAAGTACGTGTGCACCATAATATTGTCAACGAGTCCCTGAAACAAGAGACACCCATACGAGTTCTAGGTGGAGGC",
    "CTGAATCACACGCGAAACCGGGAGGCAAGCGCGTACTCTACCTTAAAGCTAGAAGCGGGTACGGTCCCCGACTAGAGATTGTTCGATAGACAATCC",
    "GGAAGTCCTTCTCACCGGTGAATTGGGCAGTTTAGGAAGTGCGCGCTTGGCTCGGAGGCATGACGGGCGCTCGTTGTTAGTAGAAGAATGAAGATA",
    "AGCGTACGCACGCTAGTATATGATGCGCTTGCAGACCCTGATTTAGTTAAGCTAAACAGTTGACGGGACCACTATAGGGCGTCATTAGCTGGACAA",
    "GCTCTTTGTCCTCAAGTTCACATTGGCGCCCCGGTTCAATAGAAGGCCCCTGCTTAACTCACCAGCTGGATACTGCACTGTCGAAACACCCTTTCG",
    "GGAGCGCCGAGCGCCGGATTCGGCGATCCTAACGACTAAAAGGAGCTCTCGAACGAGAACACCTGTACGCCTGAAAAACCAGTAAAGGTGTCTAGC",
    "GGGAAACGATCG"
);
const SPLICE_READ: &str = "ACGCCGGTACACTACGAGGCATAGGCCGCGGTCCTTACCAATGACCTTATGTGCAACTCTATCATTCCTCCCGGACGCCACCACCTTTGGCATACCGATGT";

const PAIR_GENOME: &str = concat!(
    "TTAGTTGTGCCGCAGCGAAGTAGTGCTTGAAATATGCGACCCCTAAGTAGGAGCGTATGCGCCCAGTAACCAATGCCTGTTGAGATGCCAGACGCG",
    "TAACCAAAACATAGAAACCATCAATAGACAGGTCATAATCGGTCCACCGGATCATTGGTGCATAGAGCCTGGGCGTTAACGCCCTTTATTACTAGC",
    "TTAATGGTATCACATTGACAAACACGGCATTAAGTAGCGACGAAACGGGATTTGCCTGACCGGGGAGAAGCCGGTCGATCAGCAGTGGTAATTGGA",
    "TATTAGGCCTAAACCATAATGTTCTAGCGCTCGAAATCATTGCACCACTTGCATCTTTGTTCCAGGGACGCTGTAAAACCAGATGCCTGTAAATCG",
    "TTTCAACGGGATGGTTTACCCGGAATTCTACGTATTTAATCAACGAGCTTAATGAGCTGACATTGCTGAAATGACCATGACTTAATAATCATTTAT",
    "GGAGAAGAGGCACGACCACAAGGACCCTATGGCACGGTGGGCAAGCTCCCGCCCGGTACATAACTGTCTGGACTGATTATGTCGGTACAGACTTCT",
    "TCCTGCGTATCGATTACGAGCTTATCTGAAGAAGTTTAGGGCAAAGGGACCATGGCCATTGGTGCCAATTTCGGTTCTTGTATGCTACAGTTAAAT",
    "AGAAAGGCCGCATTGTCGTTCTCGCCCTGTTTTCCTCATACACGACCGAGGTTATTTGTCGGAAACGAGACATCTCTCGAAGGTGGAACGACGCCG",
    "GGTGTGCAGAATTTATTTTAAACACTCTATTACCTCCGGGTAGCGTTGGCAAACTCCGATAATGAGCGCCAGGCGTGCCAGGACTCCACCTCCCCT",
    "GCTAAGTTGACCTTGAGCTCGGTACAGCGTCGGCGAGACGATAACAACGAAGTCCTTCGGCGTTATGTAATTCACCAGCCCACCATATCAGGTAAT",
    "AGGCTCGCTGGTTAGGTAGATTATGTAAGAGGCGTGCAGCGCCGAACGGGGGTTTCACATCGATGCATGCCACATTGGGATGGGGCTCACTGTATC",
    "AGCCGTACCGCTATCTACCTATTGGTGGAGATAGCTTTTATGCGGATTCAAGGAACATAGAGTCGTCCTGACCCTAATCGAACGCGGGGTCTCACA",
    "GACTCTCGCTAAGAAATGTGTGACGACCAGCATAGTACGATATGGGTTCATGCTAGAAAGACTAGTTTAATGAAAGGATACGAATGCCCCCCGATT",
    "ACCGGCCGCCTTGCTACATCCAAGAAAACCTATTGCCGCTACTGATTCTTCTCTTAGGGATCGAGTAACTATTTATTCCGTTCGAGGCGTACGCGG",
    "TAGTATGTCGCCAGCATTTAATCCCCCCACTGGGATGCGGCTGCTGTTGTTACCAACAGCTAAAAGTGATGGTCCACACTCTTGACTCTATATGCT",
    "ATAGTTTGCCGCGCTAATTTAGTCAGCGACACCAATTATGGAACCTGGCATGGAAGTCGTCCGCTGGTCATGTCGGTGGTGATGATCGCCGTCATT",
    "TTCTGTCGAATGTCTAATAGCGCACGACAATACACATCATACCCTTTATCTAGAGGGTCAGAAGACCTCGCTAATATTCTGCTGTAGCTCGTTATA",
    "TTCTCGTTCCTGGTCACGAACGAGCTTCTTCCTAGCGCTCTCTACTGCAAACCTCATGGTCCGGTTTGTACCACTTCGAATCATTCACTGTAATAC",
    "TGGAACAGCTGATGCTTGCGAACGTATTGTAATCCAATCAGGTAGGGCAGACTAGGCGATAGAACTACGACCCTCTGCGGCCTGCGAAGGGAAAGA",
    "CGCGTATTAATGCGCTGAAAGAGGGACCGATTGCGGTTATGCACTTACAGACCTAGTACTGGTTTACGCCCCGCCGACCTCCCCCGATCATCTTCT",
    "TACAAAACTTGTGTGACCCAAATCTCGACGGGGGCATCTGTGTCTGGGTTTGCCTCGCCTGGTGTACGTAACAGACCCGGAAACGCTTGGATAACA",
    "GGCTCGCCTCTCAATACATGGCAGCGGTTGGATCAGTTTCTCAACTGATGGAGAAAACATTTAGCATCACTAATCGTTATCCCCATGGGCTAAAAG",
    "CCCAGAGCGAAGCGTGTTAAGTTTTTACCTGCACCATAAGGGTTGTGCATGGACATAGTCAAAGAGCGGTTTACTGCATCTGTCATCTGGTCTTCG",
    "TGCCGCGTCGCGCCGCATTCCGCATCGTGCGTGAACCCTAGGTTGTAAAGCGTGTTGCAAAAGACAAAGATCCGGCCCCCCGTGCGCACTCCAGTC",
    "GAGCACCATCCTAGCCTGTCGCAGTGGGCGTACTAACTCTGCCAGTGTAGTTCCAGTTCTCTAATATCACCCATTACCCTACACCTTGTAGGCACT",
    "CCACCTTAGGTGGAATGACCTCATGCGCAGGAGCCGTTTACTAGCCTGCCTGCACCTTCAGTAGAATCAAATGGTCCACTCACCCCCAAGAGTGTA",
    "ACTAGGGTTAGCCACCCTGAGTCGTCGATGCGGAGCTATTAGTTCCAGATGCTTGTCTGCACGGAATGGCGTCACGTTCGTTTGAATCAATTCTAT",
    "AGCGGAGACAAGGTCCGTGCTTAAAAGCGAGAAGACACTCCTGCTATAAAGATCGTCTGCTATCGGGTTGGGCCCTGAGTGCAATCCTGCATTTTG",
    "ACCATCATGCATATGACGTTGAAAGTTTCGTTATGTCTTTGTGGTCGATTTGACGCTAGCCTAACACCATTCGTTGACTCAATGGGTAGGTAAGCT",
    "GCTATAAAGAGGAAAACCTACACAAAACATTAATTCACGTCAACATGGTGCACTGGGGAAACGCCCATTCGGCACGGCATCGGCACGTAGTGAGCT",
    "ATGCGAGAGTAGCCGGACTCATGAGAACGCTCCACTTGGGAATGCTCTACTTTCCTTTCGACAGCACGCTGTGTTTAGGGGGTATCTGTAATAGAA",
    "TTGTTTCAGCGTACACTCTGTCTG"
);
const PAIR_MATE1: &str = "GCCGAACGGGGGTTTCACATCGATGCATGCCACATTGGGATGGGGCTCACTGTATGCAGCCGTACCGCTATCTACCTATTGGTGGAGATAGCTTTTATGCGGATTCAAGGAACATAGAGTCGTCCTGACCCTAATCGAACGCGGGGTCTC";
const PAIR_MATE2: &str = "GGCGTCCCCATTCCGCTGCATGAGCGAGGCACCCAGTCGAGAGAAAACATGAAATGCCCTTTCTCAGCCTCGAGTTAATTGCTGGGCTACCTGAATACAGTGAGCCCCATCCCAATGTGGCATGCATCGATGTGAAACCCCCGTTCGGCA";

fn build_genome(dir: &Path, sequence: &str) -> std::path::PathBuf {
    let fasta = dir.join("genome.fa");
    writeln!(fs::File::create(&fasta).unwrap(), ">chr1\n{sequence}").unwrap();
    let genome_dir = dir.join("genome");
    fs::create_dir_all(&genome_dir).unwrap();
    cargo_bin_cmd!("rustar-aligner")
        .args(["--runMode", "genomeGenerate", "--genomeDir"])
        .arg(&genome_dir)
        .arg("--genomeFastaFiles")
        .arg(&fasta)
        .args(["--genomeSAindexNbases", "5", "--outFileNamePrefix"])
        .arg(genome_dir.join("run_"))
        .assert()
        .success();
    genome_dir
}

fn write_read(path: &Path, sequence: &str) {
    writeln!(
        fs::File::create(path).unwrap(),
        "@r1\n{sequence}\n+\n{}",
        "I".repeat(sequence.len())
    )
    .unwrap();
}

/// Aligned records as `flag pos cigar AS`.
fn align(tmp: &TempDir, reads: &[&str]) -> Vec<String> {
    let genome_dir = tmp.path().join("genome");
    let out = tmp.path().join("out");
    fs::create_dir_all(&out).unwrap();
    let mut cmd = cargo_bin_cmd!("rustar-aligner");
    cmd.args(["--runMode", "alignReads", "--genomeDir"])
        .arg(&genome_dir)
        .arg("--readFilesIn");
    for (i, seq) in reads.iter().enumerate() {
        let path = tmp.path().join(format!("r{}.fq", i + 1));
        write_read(&path, seq);
        cmd.arg(path);
    }
    cmd.arg("--outFileNamePrefix")
        .arg(format!("{}/", out.display()))
        .assert()
        .success();
    fs::read_to_string(out.join("Aligned.out.sam"))
        .unwrap()
        .lines()
        .filter(|l| !l.starts_with('@'))
        .map(|l| {
            let c: Vec<&str> = l.split('\t').collect();
            let score = c.iter().find(|t| t.starts_with("AS:i:")).unwrap();
            format!("{} {} {} {}", c[1], c[3], c[5], score)
        })
        .collect()
}

/// The first seed covers all but four bases of the exon after the junction, because
/// the intron starts with a copy of that exon's first bases. Trimmed by the overlap,
/// the second seed is shorter than `alignSJoverhangMin`, but STAR still stitches it:
/// the junction scan shifts the junction left, which lengthens the second exon again
/// (`stitchAlignToTranscript.cpp`, no early exit on the trimmed length).
#[test]
fn junction_scan_rescues_a_second_seed_trimmed_below_the_overhang_minimum() {
    let tmp = TempDir::new().unwrap();
    build_genome(tmp.path(), SPLICE_GENOME);
    assert_eq!(
        align(&tmp, &[SPLICE_READ]),
        vec!["0 1501 84M751N17M AS:i:97"]
    );
}

/// The two mates overlap and the second one ends before the first. STAR's
/// genomic-length penalty spans the first exon's start to the LAST exon's end, which
/// is the end of the second mate here, not the end of the pair
/// (`stitchWindowAligns.cpp`, `trA.exons[nExons-1]`).
#[test]
fn genomic_length_penalty_ends_at_the_last_exon_of_the_pair() {
    let tmp = TempDir::new().unwrap();
    build_genome(tmp.path(), PAIR_GENOME);
    assert_eq!(
        align(&tmp, &[PAIR_MATE1, PAIR_MATE2]),
        vec!["99 1001 55M1I94M AS:i:199", "147 1001 1S55M94S AS:i:199"]
    );
}
